/**
 * Common files generator.
 * Always runs. Generates README, .env.example, .gitignore, scripts, Makefile.
 */
import type {
  Generator,
  GeneratorContext,
  GeneratorResult,
  GeneratedFile,
  TechCategory,
  SelectedTech,
} from '../core/types.js';
import { createTemplateEngine } from '../templates/engine.js';

function hasTech(ctx: GeneratorContext, id: string): boolean {
  return ctx.selection.technologies.some((t) => t.id === id);
}

function getTech(ctx: GeneratorContext, category: TechCategory): SelectedTech | undefined {
  return ctx.selection.technologies.find((t) => t.category === category);
}

function isNodeBackend(ctx: GeneratorContext): boolean {
  return (
    hasTech(ctx, 'express') ||
    hasTech(ctx, 'fastify') ||
    hasTech(ctx, 'koa') ||
    hasTech(ctx, 'hono') ||
    hasTech(ctx, 'nestjs')
  );
}

function isPythonBackend(ctx: GeneratorContext): boolean {
  return hasTech(ctx, 'fastapi') || hasTech(ctx, 'flask') || hasTech(ctx, 'django');
}

function isGoBackend(ctx: GeneratorContext): boolean {
  return hasTech(ctx, 'gin') || hasTech(ctx, 'fiber') || hasTech(ctx, 'echo');
}

const engine = createTemplateEngine();

// ─── README ────────────────────────────────────────────────────────

function generateReadme(ctx: GeneratorContext): string {
  const name = ctx.selection.name;
  const desc = ctx.selection.description ?? 'Generated by Constellation';
  const frontend = getTech(ctx, 'frontend');
  const backend = getTech(ctx, 'backend');
  const database = getTech(ctx, 'database');
  const techs = ctx.selection.technologies.map((t) => t.id);

  const sections: string[] = [];

  sections.push(`# ${name}\n\n${desc}\n`);

  // Tech stack
  sections.push('## Tech Stack\n');
  if (frontend) sections.push(`- **Frontend:** ${frontend.id}`);
  if (backend) sections.push(`- **Backend:** ${backend.id}`);
  if (database) sections.push(`- **Database:** ${database.id}`);

  const css = getTech(ctx, 'css');
  if (css) sections.push(`- **CSS:** ${css.id}`);

  const orm = getTech(ctx, 'orm');
  if (orm) sections.push(`- **ORM:** ${orm.id}`);

  sections.push('');

  // Prerequisites
  sections.push('## Prerequisites\n');
  if (frontend || isNodeBackend(ctx)) {
    sections.push('- Node.js >= 20');
  }
  if (isPythonBackend(ctx)) {
    sections.push('- Python >= 3.13');
  }
  if (isGoBackend(ctx)) {
    sections.push('- Go >= 1.23');
  }
  if (hasTech(ctx, 'docker') || hasTech(ctx, 'podman')) {
    sections.push('- Docker');
  }
  sections.push('');

  // Getting started
  sections.push('## Getting Started\n');
  sections.push('```bash');
  sections.push('# Clone and install');
  sections.push(`cd ${name}`);

  if (hasTech(ctx, 'docker') || hasTech(ctx, 'docker-compose')) {
    sections.push('\n# Using Docker Compose');
    sections.push('docker compose up -d');
  } else {
    if (frontend || isNodeBackend(ctx)) {
      sections.push('\n# Install dependencies');
      if (frontend) sections.push('cd frontend && npm install && cd ..');
      if (isNodeBackend(ctx)) sections.push('cd backend && npm install && cd ..');
    }
    if (isPythonBackend(ctx)) {
      sections.push('\n# Python setup');
      sections.push('cd backend && pip install -r requirements.txt && cd ..');
    }
  }
  sections.push('```\n');

  // Available scripts
  sections.push('## Available Scripts\n');
  if (frontend) {
    sections.push('### Frontend\n');
    sections.push('```bash');
    sections.push('cd frontend');
    sections.push('npm run dev      # Start development server');
    sections.push('npm run build    # Build for production');
    sections.push('```\n');
  }

  if (isNodeBackend(ctx)) {
    sections.push('### Backend\n');
    sections.push('```bash');
    sections.push('cd backend');
    sections.push('npm run dev      # Start development server');
    sections.push('npm run build    # Build for production');
    sections.push('npm run start    # Start production server');
    sections.push('```\n');
  }

  if (isPythonBackend(ctx)) {
    sections.push('### Backend\n');
    sections.push('```bash');
    sections.push('cd backend');
    if (hasTech(ctx, 'fastapi')) {
      sections.push('uvicorn app.main:app --reload --port 4000');
    } else if (hasTech(ctx, 'flask')) {
      sections.push('flask run --port 4000');
    }
    sections.push('```\n');
  }

  // API endpoints
  if (backend) {
    sections.push('## API Endpoints\n');
    sections.push('| Method | Path | Description |');
    sections.push('|--------|------|-------------|');
    sections.push('| GET | /health | Health check |');
    sections.push('| GET | /api/items | List all items |');
    sections.push('| GET | /api/items/:id | Get item by ID |');
    sections.push('| POST | /api/items | Create item |');
    sections.push('| PUT | /api/items/:id | Update item |');
    sections.push('| DELETE | /api/items/:id | Delete item |');
    sections.push('');
  }

  // License
  sections.push('## License\n\nMIT\n');

  return sections.join('\n');
}

// ─── .env.example ──────────────────────────────────────────────────

function generateEnvExample(ctx: GeneratorContext): string {
  const lines: string[] = ['# Application', 'NODE_ENV=development', 'PORT=4000', ''];

  if (hasTech(ctx, 'postgresql')) {
    lines.push('# PostgreSQL');
    lines.push('DATABASE_URL=postgresql://postgres:postgres@localhost:5432/app');
    lines.push('POSTGRES_USER=postgres');
    lines.push('POSTGRES_PASSWORD=postgres');
    lines.push('POSTGRES_DB=app');
    lines.push('');
  }

  if (hasTech(ctx, 'mysql') || hasTech(ctx, 'mariadb')) {
    lines.push('# MySQL');
    lines.push('DATABASE_URL=mysql://root:root@localhost:3306/app');
    lines.push('MYSQL_ROOT_PASSWORD=root');
    lines.push('MYSQL_DATABASE=app');
    lines.push('');
  }

  if (hasTech(ctx, 'mongodb')) {
    lines.push('# MongoDB');
    lines.push('DATABASE_URL=mongodb://admin:admin@localhost:27017/app?authSource=admin');
    lines.push('MONGO_USER=admin');
    lines.push('MONGO_PASSWORD=admin');
    lines.push('');
  }

  if (hasTech(ctx, 'redis')) {
    lines.push('# Redis');
    lines.push('REDIS_URL=redis://localhost:6379');
    lines.push('');
  }

  lines.push('# CORS');
  lines.push('CORS_ORIGIN=http://localhost:3000');
  lines.push('');

  if (hasTech(ctx, 'sentry')) {
    lines.push('# Sentry');
    lines.push('SENTRY_DSN=');
    lines.push('VITE_SENTRY_DSN=');
    lines.push('');
  }

  return lines.join('\n');
}

// ─── .gitignore ────────────────────────────────────────────────────

function generateGitignore(ctx: GeneratorContext): string {
  const lines: string[] = [
    '# Dependencies',
    'node_modules/',
    '',
    '# Build output',
    'dist/',
    'build/',
    '.next/',
    '.nuxt/',
    '.output/',
    '',
    '# Environment',
    '.env',
    '.env.local',
    '.env.*.local',
    '',
    '# IDE',
    '.idea/',
    '.vscode/',
    '*.swp',
    '*.swo',
    '.DS_Store',
    '',
    '# Logs',
    '*.log',
    'logs/',
    '',
    '# Testing',
    'coverage/',
    '.nyc_output/',
    'test-results/',
    'playwright-report/',
    '',
  ];

  if (isPythonBackend(ctx)) {
    lines.push(
      '# Python',
      '__pycache__/',
      '*.py[cod]',
      '*$py.class',
      '.venv/',
      'venv/',
      '*.egg-info/',
      '',
    );
  }

  if (isGoBackend(ctx)) {
    lines.push('# Go', '*.exe', '*.test', '*.out', '');
  }

  if (hasTech(ctx, 'prisma')) {
    lines.push('# Prisma', 'prisma/*.db', '');
  }

  if (hasTech(ctx, 'docker') || hasTech(ctx, 'podman')) {
    lines.push('# Docker', '.docker/', '');
  }

  return lines.join('\n');
}

// ─── Makefile ──────────────────────────────────────────────────────

function generateMakefile(ctx: GeneratorContext): string {
  const name = ctx.selection.name;
  const targets: string[] = [];

  targets.push(`.PHONY: help dev build test clean

help: ## Show this help
\t@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\\033[36m%-20s\\033[0m %s\\n", $$1, $$2}'
`);

  if (hasTech(ctx, 'docker-compose') || hasTech(ctx, 'docker')) {
    targets.push(`up: ## Start all services with Docker Compose
\tdocker compose up -d

down: ## Stop all services
\tdocker compose down

logs: ## Tail service logs
\tdocker compose logs -f
`);
  }

  if (isNodeBackend(ctx) || getTech(ctx, 'frontend')) {
    targets.push(`install: ## Install all dependencies
\t${getTech(ctx, 'frontend') ? 'cd frontend && npm install && cd .. && ' : ''}${isNodeBackend(ctx) ? 'cd backend && npm install' : ''}
`);
  }

  targets.push(`dev: ## Start development servers
\t${getTech(ctx, 'frontend') ? 'cd frontend && npm run dev &' : ''} ${getTech(ctx, 'backend') ? 'cd backend && npm run dev' : ''}
`);

  targets.push(`build: ## Build for production
\t${getTech(ctx, 'frontend') ? 'cd frontend && npm run build && cd .. && ' : ''}${getTech(ctx, 'backend') && isNodeBackend(ctx) ? 'cd backend && npm run build' : ''}
`);

  targets.push(`test: ## Run tests
\t${isNodeBackend(ctx) ? 'cd backend && npm test' : ''}${isPythonBackend(ctx) ? 'cd backend && python -m pytest' : ''}
`);

  targets.push(`clean: ## Clean build artifacts
\trm -rf frontend/dist frontend/node_modules backend/dist backend/node_modules
`);

  return targets.join('\n');
}

// ─── setup.sh ──────────────────────────────────────────────────────

function generateSetupScript(ctx: GeneratorContext): string {
  const lines: string[] = [
    '#!/usr/bin/env bash',
    'set -euo pipefail',
    '',
    'echo "Setting up project..."',
    '',
    '# Copy environment file',
    'if [ ! -f .env ]; then',
    '  cp .env.example .env',
    '  echo "Created .env from .env.example"',
    'fi',
    '',
  ];

  if (getTech(ctx, 'frontend') || isNodeBackend(ctx)) {
    lines.push('# Check Node.js version');
    lines.push('required_node=20');
    lines.push('current_node=$(node -v | cut -d. -f1 | tr -d v)');
    lines.push('if [ "$current_node" -lt "$required_node" ]; then');
    lines.push('  echo "Error: Node.js >= $required_node is required (found v$current_node)"');
    lines.push('  exit 1');
    lines.push('fi');
    lines.push('');
  }

  if (getTech(ctx, 'frontend')) {
    lines.push('# Install frontend dependencies');
    lines.push('echo "Installing frontend dependencies..."');
    lines.push('(cd frontend && npm install)');
    lines.push('');
  }

  if (isNodeBackend(ctx)) {
    lines.push('# Install backend dependencies');
    lines.push('echo "Installing backend dependencies..."');
    lines.push('(cd backend && npm install)');
    lines.push('');
  }

  if (isPythonBackend(ctx)) {
    lines.push('# Install Python dependencies');
    lines.push('echo "Installing Python dependencies..."');
    lines.push('(cd backend && pip install -r requirements.txt)');
    lines.push('');
  }

  if (isGoBackend(ctx)) {
    lines.push('# Download Go modules');
    lines.push('echo "Downloading Go dependencies..."');
    lines.push('(cd backend && go mod tidy)');
    lines.push('');
  }

  if (hasTech(ctx, 'prisma')) {
    lines.push('# Generate Prisma client');
    lines.push('echo "Generating Prisma client..."');
    lines.push('(cd backend && npx prisma generate)');
    lines.push('');
  }

  lines.push('echo "Setup complete!"');
  lines.push('');

  return lines.join('\n');
}

// ─── Generator ─────────────────────────────────────────────────────

export function createCommonGenerator(): Generator {
  return {
    name: 'common',
    description: 'Generates common project files: README, .env.example, .gitignore, scripts, and Makefile',

    async generate(ctx: GeneratorContext): Promise<GeneratorResult> {
      const files: GeneratedFile[] = [];

      files.push({ path: 'README.md', content: generateReadme(ctx) });
      files.push({ path: '.env.example', content: generateEnvExample(ctx) });
      files.push({ path: '.gitignore', content: generateGitignore(ctx) });
      files.push({ path: 'Makefile', content: generateMakefile(ctx) });
      files.push({ path: 'scripts/setup.sh', content: generateSetupScript(ctx) });

      return {
        files,
        messages: [
          'Run `bash scripts/setup.sh` to set up the project.',
          'Copy `.env.example` to `.env` and fill in your values.',
        ],
      };
    },
  };
}
